---
# SPDX-FileCopyrightText: 2026–Present ninetailedtori <ninetailedtori@uwu.gal>
# SPDX-FileContributor: WhailMail contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

updates:
  # Frontend
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
    groups:
      frontend:
        patterns: ["*"]

  # Backend
  - package-ecosystem: "rust-toolchain"
    directory: "/backend/"
    schedule:
      interval: "weekly"
    groups:
      backend:
        patterns: ["*"]
  - package-ecosystem: "cargo"
    directory: "/backend/"
    schedule:
      interval: "weekly"
    groups:
      backend:
        patterns: ["*"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    groups:
      ci-dependencies:
        patterns: ["*"]
