---
# SPDX-FileCopyrightText: 2026-Present ninetailedtori <ninetailedtori@uwu.gal>
# SPDX-FileContributor: WhailMail contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later
overrides:
  '@vue/compat': "beta"
  '@vue/compiler-core': "beta"
  '@vue/compiler-dom': "beta"
  '@vue/compiler-sfc': "beta"
  '@vue/compiler-ssr': "beta"
  '@vue/compiler-vapor': "beta"
  '@vue/reactivity': "beta"
  '@vue/runtime-core': "beta"
  '@vue/runtime-dom': "beta"
  '@vue/runtime-vapor': "beta"
  '@vue/server-renderer': "beta"
  '@vue/shared': "beta"
  esbuild@>=0.17.0 <0.28.1: ">=0.28.1"
  esbuild@>=0.27.3 <0.28.1: ">=0.28.1"
  vue: "beta"
  ws@>=8.0.0 <8.20.1: ">=8.20.1"

peerDependencyRules:
  allowAny: ["vue"]
