# SPDX-FileCopyrightText: 2026–Present ninetailedtori <ninetailedtori@uwu.gal>
# SPDX-FileContributor: WhailMail contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
  path = [
    ".clang-format",
    ".gitignore",
    "CONTRIBUTING.md",
    "README.md",
    "meson.build",
    "meson_options.txt",
    "frontend/**",
    "backend/**",
    "include/**",
    "data/**",
  ]
  SPDX-FileCopyrightText = "2026 ninetailedtori <ninetailedtori@uwu.gal>"
  SPDX-FileContributor = "WhailMail contributors"
  SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
  path                    = [ "COPYING" ]
  precedence              = "override"
  SPDX-FileCopyrightText  = "2007 Free Software Foundation, Inc."
  SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
  path                    = [ "subprojects/*.wrap", "subprojects/packagefiles/**" ]
  SPDX-FileCopyrightText  = "2026 ninetailedtori <ninetailedtori@uwu.gal>"
  SPDX-FileContributor    = "WhailMail contributors"
  SPDX-License-Identifier = "GPL-3.0-or-later"
