# SPDX-FileCopyrightText: 2026–Present ninetailedtori <ninetailedtori@uwu.gal>
# SPDX-FileContributor: WhailMail contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

[build]
  rustflags = [
    "-C",
    "target-cpu=native",
    "-C",
    "force-frame-pointers=yes",
    "-C",
    "link-arg=-Wl,-O4,--sort-common,--as-needed,-z,relro,-z,now,-z,pack-relative-relocs",
  ]

[term]
  verbose = true
  color   = "auto"

[doc]
  open = true

[env]
  CFLAGS   = "-O3 -fPIC -fstack-protector-strong -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -Wp,-D_FORTIFY_SOURCE=3"
  CXXFLAGS = "-O3 -fPIC -fstack-protector-strong -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -Wp,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS"
  LDFLAGS  = "-Wl,-O4,--sort-common,--as-needed,-z,relro,-z,now,-z,pack-relative-relocs"

[profile.dev]
  opt-level     = 0
  debug         = true
  codegen-units = 256

[profile.release]
  opt-level     = 3
  lto           = "fat"
  codegen-units = 1
  debug         = false
  strip         = true

[profile.release-with-debug]
  inherits = "release"
  debug    = true
  strip    = false

[profile.bench]
  inherits = "release"
