# SPDX-FileCopyrightText: 2026 2026-Present ninetailedtori <ninetailedtori@uwu.gal>
# SPDX-FileContributor: WhailMail contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
  name              = "whailmail-api"
  version.workspace = true
  edition.workspace = true
  authors.workspace = true
  license.workspace = true
